import type {Metadata} from "next";

import React from "react";
import Head from "next/head";

import HeaderLayout from "@/components/layout/header.layout";

import "@/styles/index.scss";

import ReactQueryProvider from "@/react-query.provider";
import ProgressBarProviders from "@/components/progressbar.provider";
import FooterLayout from "@/components/layout/footer.layout";

import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";

import "swiper/css";
// import "swiper/css/free-mode";
import "swiper/css/navigation";
// import "swiper/css/thumbs";
import {poppins, inter} from "@/app/fonts/font";
import {Toaster} from "@/components/ui/sonner";
import QuickReviewProductComponent from "@/components/custom/quickReviewProduct.component";
import QuickReviewAddToCartComponent from "@/components/custom/quickReviewAddToCart.component";
// import {cookies} from "next/headers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale},
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <Head>
        <meta charSet="UTF-8" />
      </Head>
      <ReactQueryProvider>
        <body className={`${poppins.variable} ${inter.variable} scroll-smooth antialiased`}>
          <NextIntlClientProvider messages={messages}>
            <HeaderLayout />
            <ProgressBarProviders>{children}</ProgressBarProviders>
            <QuickReviewProductComponent />
            <QuickReviewAddToCartComponent />
            <FooterLayout />
            <Toaster closeButton richColors expand={true} position="bottom-right" />
          </NextIntlClientProvider>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
